### ISSUE TITLE
SonarQube static code checking

### ISSUE THREAD

**Issue by kissslorinc** [BME-MIT-IET/Cant-C-Sharp-iet-2018#1]

**Comment by kissslorinc** [comment]
Moved to SonarCloud, see [here](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/56f5ef6e3954f9cc84f7f853f7099baf7ee725fe), [here](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/ed26a25a10e13b974b76fae2f61d36d0ca1a1332), [here](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/624ff4cfce27e8697a90d5813685f09ca4913c7b) and [here](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/9f7007209478cd3b302fa77149e6d32eccfeeebb), or check the [wiki](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/wiki/Static-code-checking)

**Comment by MateSzoke** [comment]
SonarCloud working fine. Close this issue. Good bye.
