### ISSUE TITLE
Random number generator test split 3 pieces (attach/detach/update)

### ISSUE THREAD

**Issue by MateSzoke** [BME-MIT-IET/Cant-C-Sharp-iet-2018#11]
#10 
In random.test.js I split attach/detach/update test to 3 pieces for better scalability.
[See this:](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/fc53bcaabb3d7b7679e4b4d0c2f2ab5e78fa7059)

**Comment by matesebi** [comment]
refactor accepted and merged int o master
