### ISSUE TITLE
Add single player test in reducer.test and expand state id test

### ISSUE THREAD

**Issue by MateSzoke** [BME-MIT-IET/Cant-C-Sharp-iet-2018#14]
#13 Add single player test in reducer.test and expand state id test
I Expand '_stateID is incremented' test with one more step, and create new single player num test.
See [this](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/aa062e94b95c7601cff374ee56d98779062643de).

**Comment by matesebi** [comment]
pull request accepted
