### ISSUE TITLE
Pull request for add test costume order for 4 player at turn-order.test

### ISSUE THREAD

**Issue by MateSzoke** [BME-MIT-IET/Cant-C-Sharp-iet-2018#16]
Pull request for add test costume order for 4 player at turn-order.test
Pull request: #15 
Commit: [here](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/f4a45350a9233f92bbebd70c05f23575c9b81a75)

**Comment by matesebi** [comment]
pull request merged into master
