### ISSUE TITLE
Manual Code Review

### ISSUE THREAD

**Issue by matesebi** [BME-MIT-IET/Cant-C-Sharp-iet-2018#3]
During manual code review most of the problems listed by sonar cube are either in the generated code, not in the actual source or are commented, that the analyzer signals an error, but it's a false positive. I found one small problem in src/core/flow.js at line 485 and 486 where two variables are assigned to but then in all branches of an if-else if-else are assigned to again.

**Comment by matesebi** [comment]
Same at src/core/random.js (174):
Random.detach = function(ctx) {
  const { random, ...rest } = ctx; // eslint-disable-line no-unused-vars
  return rest;
};

**Comment by matesebi** [comment]
# #4

**Comment by matesebi** [comment]
Added fix on codereview branch and created pull request: #4

**Comment by MateSzoke** [comment]
Merged
