### ISSUE TITLE
Loose validation, potential vulnerability

### ISSUE THREAD

**Issue by AdamBelakovics** [BME-MIT-IET/Cant-C-Sharp-iet-2018#5]
https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/blob/ffdb54e8d0e8bcb853b520c040fbb3b3d9019dbf/src/client/debug/debug.js#L38

**Comment by AdamBelakovics** [comment]
Any code can be injected here due to lack of validaton.

**Comment by MateSzoke** [comment]
It's dangerous. We don't let it without words! :O

**Comment by AdamBelakovics** [comment]
Unfortunately there's no viable solution for this problem. JS compiler has to be invoked here. It is a potential vulnerability, but its for debugging, so the developer can handle this problem.
