### ISSUE TITLE
Testing deck integrity

### ISSUE THREAD

**Issue by kissslorinc** [BME-MIT-IET/Cant-C-Sharp-iet-2018#6]
Deck integrity (whether only the first card is face-up and has a hover effect) is not yet tested.

**Comment by kissslorinc** [comment]
Added new tests, see [here](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/57d3b9b066f6f1f8091d4762f75d92fee566bb28)

**Comment by MateSzoke** [comment]
I think its a great test. Good job!

**Comment by MateSzoke** [comment]
Do you want to talk about that more, or can I close this issue?

**Comment by MateSzoke** [comment]
Ok, Merged, Iclose this. Have a nice weekedn!
