### ISSUE TITLE
Testing card integrity

### ISSUE THREAD

**Issue by kissslorinc** [BME-MIT-IET/Cant-C-Sharp-iet-2018#7]
Card display integrity (whether the correct side is rendered) is not yet tested

**Comment by kissslorinc** [comment]
Added new tests, see [here](https://github.com/BME-MIT-IET/Cant-C-Sharp-iet-2018/commit/dcc2e3a646c77fb6ee51bdb794aa36c5a703ce1d)

**Comment by MateSzoke** [comment]
Tests was great, merged to master, I close this issue. Bye
